name: deploy to lambda
on:
  push:
    branches:
      - use-ssm-param-store
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci --production
          npm run build
        env:
          CI: true
      - name: zip
        run: |
          mkdir temp
          cp -r ./node_modules temp/node_modules
          cp -r ./build temp/build
          cp -r ./index.js temp/index.js
          cd temp
          zip -qq -r ../bundle.zip *
          rm -rf temp
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-southeast-1
          function_name: bitbucket_pull_reminder
          zip_file: bundle.zip
